version: '3.8'

services:
  frontend: 
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend
  backend: 
    image: backend
    ports:
      - 8080:8080
    environment:
     - REDIS_HOST=cache
     - POSTGRES_HOST=db
     - POSTGRES_USER=tatu
     - POSTGRES_PASSWORD=example
     - POSTGRES_DATABASE=tatu
    depends_on:
     - db
    container_name: backend
  cache:
    image: redis
    restart: unless-stopped
    container_name: redis-cache
  db:
    image: postgres
    restart: unless-stopped
    environment:
     - POSTGRES_USER=tatu
     - POSTGRES_PASSWORD=example
    container_name: database
