version: '3.8'

services:
  frontend: 
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend
  backend: 
    image: backend
    ports:
      - 8080:8080
    environment:
     - REDIS_HOST=cache
    container_name: backend
  cache:
    image: redis:latest
    restart: unless-stopped
    container_name: redis-cache