version: '3.8'

services:
  frontend: 
    image: frontend
    container_name: frontend
  backend: 
    image: backend
    environment:
     - REDIS_HOST=cache
     - POSTGRES_HOST=db
     - POSTGRES_USER=tatu
     - POSTGRES_PASSWORD=example
     - POSTGRES_DATABASE=tatu
    depends_on:
     - db
    container_name: backend
  cache:
    image: redis
    restart: unless-stopped
    volumes:
     - ./redisdata:/data
    container_name: redis-cache
  db:
    image: postgres
    restart: unless-stopped
    environment:
     - POSTGRES_USER=tatu
     - POSTGRES_PASSWORD=example
    volumes:
     - ./database:/var/lib/postgresql/data
    container_name: database
  proxy:
    image: nginx
    ports:
     - 80:80
    environment:
     - NGINX_HOST=http://localhost
     - NGINX_PORT=80
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: proxy
